version: '3.3'
services:
  web:
    image: tubes-1:latest
    volumes:
      - ./src/server:/var/www
      - ./src/public:/var/www/html
    ports:
      - 8008:80
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./src/migration:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"
    env_file:
      - .env
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
